# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: WeltWeb
# Description of the Site
description: Eleva il tuo sito web con noi
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: WeltWeb, Web Designer, Website Designer, Website Developer, Web Developer, Web Creation, Site Design, Site Development, Sviluppatori Web, Sviluppatori siti
# URL for the Image of custom Favicon
favicon-url: https://i.ibb.co/Zp1ByCJv/download.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: info@weltweb.eu
facebook_username: weltweb
twitter_username: weltweb
instagram_username: weltweb
linkedin_username: weltweb
github_username:  weltweb
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: weltweb

# Name of the Author
author-name: WeltWeb
# URL for the Image of the Author
author-image: https://i.ibb.co/Zp1ByCJv/download.png
# 60 Words About the Author
author-about: |
  Web Developer Professionali
  Eleva il tuo sito con noi
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://weltweb.eu

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
